os:
  - linux

language: nix

sudo: required

git:
  depth: 1

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - "result/*.pdf"
  skip_cleanup: true
  on:
    tags: true
